# Generated by Django 4.2.6 on 2023-10-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bidId', models.IntegerField(primary_key=True, serialize=False)),
                ('itemId', models.IntegerField()),
                ('contribution', models.JSONField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('bidPlacedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255)),
                ('categoryDescription', models.CharField(max_length=255)),
                ('categoryImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=40)),
                ('userId', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('auctionStartTime', models.DateTimeField()),
                ('auctionDuration', models.DateTimeField()),
                ('startingBid', models.PositiveBigIntegerField()),
                ('saleStatus', models.BooleanField(default=False)),
                ('costPrice', models.PositiveIntegerField(null=True)),
                ('itemImage', models.ImageField(upload_to='')),
                ('categoryName', models.CharField(max_length=40)),
                ('bidders', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('itemId', models.IntegerField()),
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('userId', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('walletAddress', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
