# Generated by Django 4.2.6 on 2023-11-03 16:32

import Auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImage',
            field=models.ImageField(upload_to=Auction.models.user_upload_path_category),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemImage',
            field=models.ImageField(upload_to=Auction.models.user_upload_path_items),
        ),
    ]
