# Generated by Django 4.2.6 on 2023-11-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_alter_category_categoryimage_alter_items_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='bidders',
            field=models.JSONField(default=[]),
        ),
    ]
