# Generated by Django 4.2.6 on 2023-11-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0004_alter_items_auctionduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='bidders',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='costPrice',
            field=models.IntegerField(null=True),
        ),
    ]
