# Generated by Django 4.2.6 on 2023-11-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0007_alter_bids_amount_alter_bids_bidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='timeBuffer',
            field=models.DateTimeField(default='2023-01-01T00:00:00'),
        ),
    ]
