# Generated by Django 4.2.6 on 2023-11-03 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0009_remove_items_auctionduration_items_auctionendtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='timeBuffer',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 19, 5, 25, 265932, tzinfo=datetime.timezone.utc)),
        ),
    ]
