# Generated by Django 4.2.6 on 2023-11-03 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0010_alter_items_timebuffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='timeBuffer',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 20, 37, 48, 404013, tzinfo=datetime.timezone.utc)),
        ),
    ]
